server:
    port: 50059
    host: localhost
    log_level: WARNING
database:
    host: "adempiere_database_host"
    port: 5432
    name: "adempiere_database_value"
    user: "adempiere_user_value"
    password: "adempiere_pass_value"
    type: PostgreSQL
