server:
    port: 50059
    host: localhost
    log_level: WARNING
database:
    host: "adempiere_database_host"
    port: 5432
    name: "adempiere_database_value"
    user: "adempiere_user_value"
    password: "adempiere_pass_value"
    type: PostgreSQL
    idle_timeout: fill_idle_timeout
    minimum_idle: fill_minimum_idle
    maximum_pool_size: fill_maximum_pool_size
    connection_timeout: fill_connection_timeout
    maximum_lifetime: fill_maximum_lifetime
    keepalive_time: fill_keepalive_time
    connection_test_query: fill_connection_test_query
