# This workflow will build a Java project with Gradle
# This file was contributed by ysenih@erpya.com from ERP Consultores y Asociados, C.A
# This file was contributed by EdwinBetanc0urt@outlook.com https://github.com/EdwinBetanc0urt
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish Project

permissions:
  contents: write # to upload release assets
  packages: write # to publish packages

on:
  release:
    types:
      - created

jobs:

  # Build dist application adempiere-processors-service
  build-app:
    name: Build ADempiere Processors Service
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 17
          architecture: x64

      - name: Setup Gradle 9
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.0.0 # current

      - name: Set Version Properties
        run: |
          echo "MAIN_VERSION=${{ github.event.release.name }}" >> src/main/java/org/spin/base/version.properties
          echo "DATE_VERSION=$(date +'%Y-%m-%d')" >> src/main/java/org/spin/base/version.properties
          echo "IMPLEMENTATION_VERSION=${{ github.event.release.tag_name }}" >> src/main/java/org/spin/base/version.properties

      - name: Create Release with Gradle
        run: gradle createRelease --warning-mode all --stacktrace
        env:
          ORG_GRADLE_PROJECT_deployUsername: ${{ secrets.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_deployToken: ${{ secrets.DEPLOY_TOKEN }}
          ORG_GRADLE_PROJECT_deplyRepository: ${{ secrets.DEPLOY_REPOSITORY }}
          GITHUB_DEPLOY_USER: ${{ github.actor }}
          GITHUB_DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DEPLOY_REPOSITORY: ${{ secrets.DEPLOY_REPOSITORY }}

      - name: Prepare flat artifacts
        run: |
          mkdir -p flat_artifacts/
          cp build/descriptors/adempiere-processors-service.dsc flat_artifacts/ || echo "Warning: .dsc file not found"
          cp build/release/adempiere-processors-service.* flat_artifacts/ || echo "Warning: release files not found"
          cp docker-compose/envoy/envoy.yaml flat_artifacts/ || echo "Warning: envoy.yaml not found"
          cp resources/env.yaml flat_artifacts/ || echo "Warning: env.yaml not found"
          ls -la flat_artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: flat_artifacts/*
          retention-days: 1



  publish-binaries:
    name: Publish Release Assets
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: artifacts/

      - name: List Assets
        run: |
          tree artifacts

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            artifacts/adempiere-processors-service.dsc
            artifacts/envoy.yaml
            artifacts/env.yaml
            artifacts/adempiere-processors-service.zip.MD5
            artifacts/adempiere-processors-service.zip
            artifacts/adempiere-processors-service.tar.MD5
            artifacts/adempiere-processors-service.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  # Check secrets to push image in docker hub registry
  check-docker-secrets:
    name: Check if docker hub registry information was set on secrets
    needs:
      - build-app
    runs-on: ubuntu-latest
    outputs:
      is_have_secrets: ${{ steps.check_secret_job.outputs.is_have_secrets }}
    steps:
      - id: check_secret_job
        run: |
          if [[ "${{ secrets.DOCKER_HUB_REPO_NAME }}" != "" && \
                "${{ secrets.DOCKER_USERNAME }}" != "" && \
                "${{ secrets.DOCKER_TOKEN }}" != "" ]]; \
          then
            echo "Secrets to use a container registry are configured in the repo"
            echo "is_have_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "Secrets to use a container registry were not configured in the repo"
            echo "is_have_secrets=false" >> $GITHUB_OUTPUT
          fi

  # TODO: Download .tar and add docker image without uncompress
  # Publish docker alpine image in Docker Hub Registry to application
  push-alpine-imame-dhr:
    name: Push docker alpine image to Docker Hub
    needs:
      - check-docker-secrets
    # Skip step based on secret
    if: needs.check-docker-secrets.outputs.is_have_secrets == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: artifacts/

      - name: Unzip Asset
        run: |
          tree artifacts
          unzip artifacts/adempiere-processors-service.zip -d docker/

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker Alpine Tags
        id: set_tags_alpine
        run: |
          # Get the release type
          IS_PRE_RELEASE=${{ github.event.release.prerelease }}
          # Set the base tags, always include the specific version tag
          TAGS="${{ secrets.DOCKER_HUB_REPO_NAME }}:${{ github.event.release.tag_name }}-alpine"
          # If it's not a pre-release, add the "latest" tag
          if [[ "$IS_PRE_RELEASE" == "false" ]]; then
            TAGS+=",${{ secrets.DOCKER_HUB_REPO_NAME }}:alpine"
          fi
          # Set the output variable for the next step to use
          echo "tags_to_push=$TAGS" >> $GITHUB_OUTPUT

      - name: Push alpine image in Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/alpine.Dockerfile
          push: true
          tags: ${{ steps.set_tags_alpine.outputs.tags_to_push }}

  # TODO: Download .tar and add docker image without uncompress
  # Publish docker multiplatform image in Docker Hub Registry to application
  push-imame-dhr:
    name: Push docker ubuntu multiplatform image to Docker Hub
    needs:
      - check-docker-secrets
    # Skip step based on secret
    if: needs.check-docker-secrets.outputs.is_have_secrets == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: artifacts/

      - name: Unzip Asset
        run: |
          tree artifacts
          unzip artifacts/adempiere-processors-service.zip -d docker/

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker Tags
        id: set_tags
        run: |
          # Get the release type
          IS_PRE_RELEASE=${{ github.event.release.prerelease }}
          # Set the base tags, always include the specific version tag
          TAGS="${{ secrets.DOCKER_HUB_REPO_NAME }}:${{ github.event.release.tag_name }}"
          # If it's not a pre-release, add the "latest" tag
          if [[ "$IS_PRE_RELEASE" == "false" ]]; then
            TAGS+=",${{ secrets.DOCKER_HUB_REPO_NAME }}:latest"
          fi
          # Set the output variable for the next step to use
          echo "tags_to_push=$TAGS" >> $GITHUB_OUTPUT

      - name: Push ubuntu image in Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/ubuntu.Dockerfile
          platforms: linux/amd64,linux/amd64/v2,linux/arm64/v8
          push: true
          tags: ${{ steps.set_tags.outputs.tags_to_push }}
